@startuml
title RK0 Scheduler Class Diagram
left to right direction
skinparam classAttributeIconSize 0
skinparam packageStyle rectangle
hide empty members

package "Scheduler Core" {
  class RKScheduler <<core>> {
    +RK_TCB  tasks[RK_CONF_N_TASKS]
    +RK_TCBQ readyQueue[UP TO 32 ENTRIES]
    +RK_TASK_HANDLE runningTask;
    --
    +kInit()
    +kYield()
    +kSchLock()
    +kSchUnlock()
  }
}

package "Kernel Objects" {
  class RK_LIST <<interface>> {
    +RK_NODE listDummy
    +ULONG size
  }

  class RK_TCBQ <<alias>> {
    +ULONG size
  }

  class RK_NODE <<kernel object>> {
    +RK_NODE* nextPtr
    +RK_NODE* prevPtr
  }

  class RK_TIMEOUT_NODE <<kernel object>> {
    +RK_TIMEOUT_NODE* nextPtr
    +RK_TIMEOUT_NODE* prevPtr
    +UINT timeoutType
    +RK_TICK timeout
    +RK_TICK dtick
    +RK_LIST* waitingQueuePtr
  }

  class RK_TCB <<kernel object>> {
   "Task Control Block"
  }

  class RK_RUNTIME <<kernel object>> {
    +RK_TICK globalTick
    +UINT nWraps
  }
}

RK_TCBQ --|> RK_LIST
RK_LIST *-- RK_NODE : listDummy
RK_TCB *-- RK_NODE : tcbNode
RK_TCB *-- RK_TIMEOUT_NODE : timeoutNode
RK_TIMEOUT_NODE --> RK_LIST : waitingQueuePtr

RKScheduler *-- RK_RUNTIME : runTime
RKScheduler *-- RK_TCB : tcbs
RKScheduler *-- RK_TCBQ : readyQueue
RKScheduler --> RK_TCB : runPtr

RK_TCBQ ..> RK_TCB : enqueue/dequeue

@enduml
